# Generated by Django 3.1.1 on 2021-03-26 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agents',
            options={'verbose_name_plural': 'Agent'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Property'},
        ),
        migrations.AddField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('', 'Choose An Offer Type')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='agents',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/profile'),
        ),
        migrations.AlterField(
            model_name='agents',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_img1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/properties', verbose_name='Property Image 1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_img2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/properties', verbose_name='Property Image 2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_img3',
            field=models.FileField(blank=True, null=True, upload_to='uploads/properties', verbose_name='Property Image 3'),
        ),
    ]
