# Generated by Django 3.1.1 on 2021-03-29 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_view', '0006_property_prize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='MoreProfile',
        ),
        migrations.AlterModelOptions(
            name='moreprofile',
            options={'verbose_name_plural': 'User Profile'},
        ),
    ]
