# Generated by Django 3.1.1 on 2021-03-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_view', '0008_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-03-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
